#pragma once

#define MONODUCK_VERSION     "1.0.4"
#define MONODUCK_VERSION_W  L"1.0.4"
#define MONODUCK_NAME        "MONODUCK " MONODUCK_VERSION
#define MONODUCK_NAME_W     L"MONODUCK " MONODUCK_VERSION_W
